apiVersion: v1
kind: Namespace
metadata:
  name: ruoyi-cloud

---
# MySQL & Nacos 共享 Secret
apiVersion: v1
kind: Secret
metadata:
  name: ruoyi-mysql-secret
  namespace: ruoyi-cloud
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "password"
  MYSQL_DATABASE: "ry-cloud"

---
apiVersion: v1
kind: Secret
metadata:
  name: ruoyi-nacos-secret
  namespace: ruoyi-cloud
type: Opaque
stringData:
  NACOS_AUTH_TOKEN: "your_auth_token"
  NACOS_AUTH_IDENTITY_KEY: "your_identity_key"
  NACOS_AUTH_IDENTITY_VALUE: "your_identity_value"
