apiVersion: v1
kind: Secret
metadata:
  name: ruoyi-secret
  namespace: ruoyi
type: Opaque
stringData:
  mysql-root-password: "password"
  nacos-auth-token: "your_auth_token"
  nacos-identity-key: "your_identity_key"
  nacos-identity-value: "your_identity_value"
